language: python
cache: pip
git:
  depth: 5
matrix:
  include:
  - python: '3.5'
    env: TOXENV=lint
  - python: '3.5'
    env: TOXENV=py35
  - python: '3.6'
    env: TOXENV=py36
  - python: '3.7'
    dist: xenial
    sudo: true
    env: TOXENV=py37
    - python: '3.8'
    dist: xenial
    sudo: true
    env: TOXENV=py38
  fast_finish: true
install:
  - pip install tox coveralls
script:
  - tox -e $TOXENV
after_success:
  - coveralls
